### 查询所有学生
GET http://localhost:8080/students


### 根据 ID 查询学生
GET http://localhost:8080/students/1


### 分页条件查询学生
GET http://localhost:8080/students/page?pageNum=1&pageSize=2


### 按姓名查询
GET http://localhost:8080/students/page?pageNum=1&pageSize=10&name=胡


### 按专业查询
GET http://localhost:8080/students/page?pageNum=1&pageSize=10&major=计算机


### 新增学生
POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "赵六",
  "age": 23,
  "major": "网络工程"
}


### 修改学生
PUT http://localhost:8080/students/1
Content-Type: application/json

{
  "name": "张三丰",
  "age": 24,
  "major": "数据科学"
}


### 删除学生
DELETE http://localhost:8080/students/1


### 参数校验测试
POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "",
  "age": -10,
  "major": ""
}

### 用户注册
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 用户登录：密码错误
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "111111"
}
### 用户登录成功
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 用户登录：用户名不存在
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "notfound",
  "password": "123456"
}

### 用户登录
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "test02",
  "password": "123456"
}

### 测试后端权限
POST http://localhost:8080/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDEiLCJ1c2VySWQiOjMsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgwMzg0ODIxLCJleHAiOjE3ODA0NzEyMjF9.AEMoBOzTQ9zXJBXsISE1Z7TyNvlTNZQhNrWTrXzQJIw

{
"name": "测试用户11",
"age": 20,
"major": "软件技术"
}
###测试查询用户列表
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwNjQxMzU3LCJleHAiOjE3ODA3Mjc3NTd9.Ur9b7SHK0kdpNIyX5Ign0p2fvO4cgRA5VXLkc9rMF5I

###测试修改角色
PUT http://localhost:8080/users/3/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwNjQxMzU3LCJleHAiOjE3ODA3Mjc3NTd9.Ur9b7SHK0kdpNIyX5Ign0p2fvO4cgRA5VXLkc9rMF5I

{
  "role": "ADMIN"
}

###测试普通用户不能访问
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDIiLCJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgwNjQxNjUyLCJleHAiOjE3ODA3MjgwNTJ9.WJptidgcqnvlHNNvytv1PFcAG-sNCs-Z4lYMGCnB6k4


###用旧 token 测试接口
GET http://localhost:8080/students/page?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwNzQyOTQ0LCJleHAiOjE3ODA4MjkzNDR9.46uRON_5A_1MRBeX999GSb8lmWTpJ6y07YtQDJls6iI

###测试
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}
###测试2
GET http://localhost:8080/students/page?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwNzQzNzc0LCJleHAiOjE3ODA4MzAxNzR9.4i99bArubzwnh2aEZSuYDKp6la6nJ1Dm0n0FaKTQAHE


### 上传学生头像
POST http://localhost:8080/upload/image
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDIiLCJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgwOTIwMjE3LCJleHAiOjE3ODEwMDY2MTd9.2qnYjse5gdAxGCjMsepUkzgLWnwis5fm3ptQJAfwmjY
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.png"
Content-Type: image/png

< D:/New_java/student-system/student-api/test-avatar.png
--WebAppBoundary--

### 不带 token 上传头像，预期返回 401
POST http://localhost:8080/upload/image
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/png

< D:/New_java/student-system/student-api/test-avatar.png
--WebAppBoundary--
###非法avatar
POST http://localhost:8080/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwOTIxNjkxLCJleHAiOjE3ODEwMDgwOTF9.5XurOLSwZJwV1RzZGRRK5HCWsfaucFt-qZdQGb47MSA

{
  "name": "非法头像测试",
  "age": 22,
  "major": "网络工程",
  "avatar": "http://abc.com/a.png"
}

###无头像测试
POST http://localhost:8080/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgwOTIxNjkxLCJleHAiOjE3ODEwMDgwOTF9.5XurOLSwZJwV1RzZGRRK5HCWsfaucFt-qZdQGb47MSA

{
"name": "无头像测试",
"age": 20,
"major": "软件工程",
"avatar": ""
}



### 普通用户导出学生 Excel，应该失败
GET http://localhost:8080/students/export
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDIiLCJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgxMDg3NjgxLCJleHAiOjE3ODExNzQwODF9.1xkIKQ0_ueReR0BWB7SItWlitbbvVYD5WUV4zz_8qgE



$token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMDg2NjMyLCJleHAiOjE3ODExNzMwMzJ9.NYP50xtkCSIXdSzm9o9rUAOWh2SqHkYBP5slq-eTjf4"

Invoke-WebRequest `
  -Uri "http://localhost:8080/students/export" `
  -Headers @{ Authorization = "Bearer $token" } `
  -OutFile "D:\New_java\student-system\学生信息.xlsx"

### 管理员导入学生 Excel
POST http://localhost:8080/students/import
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDIiLCJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgxMDkyOTQ1LCJleHAiOjE3ODExNzkzNDV9.f6hmzqgczpaXrmpnGbALoWOS44dO8HYCr_LjkLZThB8
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="导入学生测试数据.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< D:\New_java\student-system\导入学生测试数据.xlsx
--WebAppBoundary--


### 下载学生导入模板
GET http://localhost:8080/students/import-template
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NCwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMTc4NjU3LCJleHAiOjE3ODEyNjUwNTd9.fHvBNfJ47Wxv6bdKKvw2OzBw6Rj_jgNAGkIGZ4coYvI
